### ISSUE TITLE
ReID模型執行失敗問題

### ISSUE THREAD

**Issue by JasonWang0048** [ricky-696/AICUP_Baseline_BoT-SORT#11]
您好，我們在執行reid模型於第59個epoch跑完時出現錯誤
以下是錯誤訊息：
start epoch 59
iter 44080
iter 44100
iter 44120
iter 44140
iter 44160
iter 44180
iter 44200
iter 44220
iter 44240
iter 44260
iter 44280
iter 44300
iter 44320
iter 44340
iter 44360
iter 44380
iter 44400
iter 44420
iter 44440
iter 44460
iter 44480
iter 44500
iter 44520
iter 44540
iter 44560
iter 44580
iter 44600
iter 44620
iter 44640
iter 44660
iter 44680
iter 44700
iter 44720
iter 44740
iter 44760
iter 44780
iter 44800
make: Entering directory '/home/mlsp01/BME/AICUP_Baseline_BoT-SORT/fast_reid/fastreid/evaluation/rank_cylib'
python3 setup.py build_ext --inplace
Compiling rank_cy.pyx because it changed.
Compiling roc_cy.pyx because it changed.
[1/2] Cythonizing rank_cy.pyx
/home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/mlsp01/BME/AICUP_Baseline_BoT-SORT/fast_reid/fastreid/evaluation/rank_cylib/rank_cy.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
[2/2] Cythonizing roc_cy.pyx
/home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/mlsp01/BME/AICUP_Baseline_BoT-SORT/fast_reid/fastreid/evaluation/rank_cylib/roc_cy.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
performance hint: roc_cy.pyx:63:24: Index should be typed for more efficient access
performance hint: roc_cy.pyx:64:25: Index should be typed for more efficient access
performance hint: roc_cy.pyx:70:23: Index should be typed for more efficient access
performance hint: roc_cy.pyx:71:49: Index should be typed for more efficient access
performance hint: roc_cy.pyx:73:25: Index should be typed for more efficient access
performance hint: roc_cy.pyx:74:49: Index should be typed for more efficient access
In file included from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
                 from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from rank_cy.c:1249:
/home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
In file included from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
                 from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from roc_cy.c:1249:
/home/mlsp01/anaconda3/envs/botsort1/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
rm -rf build
make: Leaving directory '/home/mlsp01/BME/AICUP_Baseline_BoT-SORT/fast_reid/fastreid/evaluation/rank_cylib'
Exception during training:
Traceback (most recent call last):
  File "./fast_reid/fastreid/engine/train_loop.py", line 151, in train
    self.after_epoch()
  File "./fast_reid/fastreid/engine/train_loop.py", line 185, in after_epoch
    h.after_epoch()
  File "./fast_reid/fastreid/engine/hooks.py", line 377, in after_epoch
    self._do_eval()
  File "./fast_reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "./fast_reid/fastreid/engine/defaults.py", line 305, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fast_reid/fastreid/engine/defaults.py", line 441, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "./fast_reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "./fast_reid/fastreid/evaluation/reid_evaluation.py", line 107, in evaluate
    cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "./fast_reid/fastreid/evaluation/rank.py", line 198, in evaluate_rank
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery
Traceback (most recent call last):
  File "fast_reid/tools/train_net.py", line 60, in <module>
    args=(args,),
  File "./fast_reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "fast_reid/tools/train_net.py", line 47, in main
    return trainer.train()
  File "./fast_reid/fastreid/engine/defaults.py", line 350, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "./fast_reid/fastreid/engine/train_loop.py", line 151, in train
    self.after_epoch()
  File "./fast_reid/fastreid/engine/train_loop.py", line 185, in after_epoch
    h.after_epoch()
  File "./fast_reid/fastreid/engine/hooks.py", line 377, in after_epoch
    self._do_eval()
  File "./fast_reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "./fast_reid/fastreid/engine/defaults.py", line 305, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fast_reid/fastreid/engine/defaults.py", line 441, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "./fast_reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "./fast_reid/fastreid/evaluation/reid_evaluation.py", line 107, in evaluate
    cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "./fast_reid/fastreid/evaluation/rank.py", line 198, in evaluate_rank
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery

我們不清楚這段訊息所提出的rank_cy.pyx檔案中,為何會出現Error: all query identities do not appear in gallery?

**Comment by ricky-696** [comment]
在[Readme的Important部分](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT?tab=readme-ov-file#train-the-reid-module-for-aicup)已經詳細解釋此問題，請先把文檔全部看完。

簡單來說，你的模型已經訓練好了
