### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Rzerooooo** [ricky-696/AICUP_Baseline_BoT-SORT#14]
在跑第50個epco中出現以下錯誤
==========================================================
Traceback (most recent call last):
  File "C:\contest\AICUP_Baseline_BoT-SORT-main\yolov7\train.py", line 613, in <module>
    train(hyp, opt, device, tb_writer)
  File "C:\contest\AICUP_Baseline_BoT-SORT-main\yolov7\train.py", line 366, in train
    loss, loss_items = compute_loss_ota(pred, targets.to(device), imgs)  # loss scaled by batch_size
  File "./yolov7\utils\loss.py", line 585, in __call__
    bs, as_, gjs, gis, targets, anchors = self.build_targets(p, targets, imgs)
  File "./yolov7\utils\loss.py", line 677, in build_targets
    b, a, gj, gi = indices[i]
IndexError: list index out of range

**Comment by ricky-696** [comment]
你應該是預訓練權重放錯了，p5模型用`train.py`，p6模型要用`train_aux.py`訓練，這我在[Readme](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT?tab=readme-ov-file#fine-tune-yolov7-for-aicup)上也有詳細說明。

這種問題Google搜尋一下就有答案了: https://github.com/WongKinYiu/yolov7/issues/1349

如果你真的是權重放錯，那發Issue前，自己是不是要先Survey一下?
