### ISSUE TITLE
python fast_reid/tools/train_net.py --config-file fast_reid/configs/AICUP/bagtricks_R50-ibn.yml MODEL.DEVICE "cuda:0" 有bug

### ISSUE THREAD

**Issue by skylol0716** [ricky-696/AICUP_Baseline_BoT-SORT#15]
Traceback (most recent call last):
  File "fast_reid/tools/train_net.py", line 13, in <module>
    from fast_reid.fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch
  File ".\fast_reid\fastreid\engine\__init__.py", line 13, in <module>
    from .hooks import *
  File ".\fast_reid\fastreid\engine\hooks.py", line 16, in <module>
    from fast_reid.fastreid.evaluation.testing import flatten_results_dict
  File ".\fast_reid\fastreid\evaluation\__init__.py", line 2, in <module>
    from .reid_evaluation import ReidEvaluator
  File ".\fast_reid\fastreid\evaluation\reid_evaluation.py", line 18, in <module>
    from fast_reid.fastreid.utils.compute_dist import build_dist
  File ".\fast_reid\fastreid\utils\compute_dist.py", line 10, in <module>
    import faiss
  File "C:\Users\user\anaconda3\envs\botsort2\lib\site-packages\faiss\__init__.py", line 51, in <module>
    from faiss.extra_wrappers import kmin, kmax, pairwise_distances, rand, randint, \
  File "C:\Users\user\anaconda3\envs\botsort2\lib\site-packages\faiss\extra_wrappers.py", line 118, in <module>
    rand_smooth_vectors_c = rand_smooth_vectors
NameError: name 'rand_smooth_vectors' is not defined
以上是error的信息
想問一下是需要去條動甚麼參數嗎

**Comment by ricky-696** [comment]
我提供的環境有rand_smooth_vectors這個函數，你應該是[Step 7](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT?tab=readme-ov-file#setup-with-conda)沒有做好

如果你有安裝但有這個問題，你試著幫我安裝下面的版本:
`pip install faiss-cpu==1.7.4`
`pip install faiss-gpu==1.7.2`
