### ISSUE TITLE
fast_reid bug

### ISSUE THREAD

**Issue by seveCh** [ricky-696/AICUP_Baseline_BoT-SORT#16]
請問我要訓練fast_reid，但我使用python3 fast_reid/tools/train_net.py  ....的指令跑，他不會報錯或顯示結果，改用python fast_reid/tools/train_net.py .....跑，結果如下，他在GPU available是false的，要怎麼改成true，及我最下面顯示說Torch不支援我的cuda，我的cuda是裝12.4版本，

(botsort) E:\Python\ML\AI_CUP\AICUP_Baseline_BoT-SORT>python fast_reid/tools/train_net.py --config-file fast_reid\configs\AICUP\bagtricks_R50-ibn.yml  MODEL.DEVICE "cuda:0"                                             
Command Line Args: Namespace(config_file='fast_reid\\configs\\AICUP\\bagtricks_R50-ibn.yml', dist_url='tcp://127.0.0.1:49153', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['MODEL.DEVICE', 'cuda:0'], resume=False)
[05/17 12:49:51 fastreid]: Rank of current process: 0. World size: 1
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4'
[05/17 12:49:51 fastreid]: Environment info:
-------------------  -----------------------------------------------------------------------------------------------
sys.platform         win32
Python               3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)]
numpy                1.21.6
fastreid             failed to import
FASTREID_ENV_MODULE  <not set>
PyTorch              1.13.1 @C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torch
PyTorch debug build  False
GPU available        False
Pillow               9.2.0
torchvision          0.14.1 @C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torchvision
cv2                  4.9.0
-------------------  -----------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

[05/17 12:49:51 fastreid]: Command line arguments: Namespace(config_file='fast_reid\\configs\\AICUP\\bagtricks_R50-ibn.yml', dist_url='tcp://127.0.0.1:49153', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=['MODEL.DEVICE', 'cuda:0'], resume=False)
[05/17 12:49:51 fastreid]: Contents of args.config_file=fast_reid\configs\AICUP\bagtricks_R50-ibn.yml:
_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    POOL_LAYER: GeneralizedMeanPooling

  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("AICUP",)
  TESTS: ("AICUP",)

SOLVER:
  BIAS_LR_FACTOR: 1.

  IMS_PER_BATCH: 256
  MAX_EPOCH: 60
  STEPS: [30, 50]
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 60 # We didn't provide eval dataset
  IMS_PER_BATCH: 256

OUTPUT_DIR: logs/AICUP_115/bagtricks_R50-ibn

[05/17 12:49:51 fastreid]: Running with full config:
CUDNN_BENCHMARK: True
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER_TRAIN: NaiveIdentitySampler
  SET_WEIGHT: []
DATASETS:
  COMBINEALL: False
  NAMES: ('AICUP',)
  TESTS: ('AICUP',)
INPUT:
  AFFINE:
    ENABLED: False
  AUGMIX:
    ENABLED: False
    PROB: 0.0
  AUTOAUG:
    ENABLED: False
    PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: False
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  CROP:
    ENABLED: False
    RATIO: [0.75, 1.3333333333333333]
    SCALE: [0.16, 1]
    SIZE: [224, 224]
  FLIP:
    ENABLED: True
    PROB: 0.5
  PADDING:
    ENABLED: True
    MODE: constant
    SIZE: 10
  REA:
    ENABLED: True
    PROB: 0.5
    VALUE: [123.675, 116.28, 103.53]
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [256, 256]
  SIZE_TRAIN: [256, 256]
KD:
  EMA:
    ENABLED: False
    MOMENTUM: 0.999
  MODEL_CONFIG: []
  MODEL_WEIGHTS: []
MODEL:
  BACKBONE:
    ATT_DROP_RATE: 0.0
    DEPTH: 50x
    DROP_PATH_RATIO: 0.1
    DROP_RATIO: 0.0
    FEAT_DIM: 2048
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    PRETRAIN: True
    PRETRAIN_PATH:
    SIE_COE: 3.0
    STRIDE_SIZE: (16, 16)
    WITH_IBN: True
    WITH_NL: False
    WITH_SE: False
  DEVICE: cuda:0
  FREEZE_LAYERS: []
  HEADS:
    CLS_LAYER: Linear
    EMBEDDING_DIM: 0
    MARGIN: 0.0
    NAME: EmbeddingHead
    NECK_FEAT: before
    NORM: BN
    NUM_CLASSES: 0
    POOL_LAYER: GeneralizedMeanPooling
    SCALE: 1
    WITH_BNNECK: True
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss', 'TripletLoss')
    TRI:
      HARD_MINING: False
      MARGIN: 0.0
      NORM_FEAT: False
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  QUEUE_SIZE: 8192
  WEIGHTS:
OUTPUT_DIR: logs/AICUP_115/bagtricks_R50-ibn
SOLVER:
  AMP:
    ENABLED: False
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 1
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 5.0
    ENABLED: False
    NORM_TYPE: 2.0
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 1e-07
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 256
  MAX_EPOCH: 60
  MOMENTUM: 0.9
  NESTEROV: False
  OPT: Adam
  SCHED: MultiStepLR
  STEPS: [30, 50]
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 60
  FLIP:
    ENABLED: False
  IMS_PER_BATCH: 256
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC:
    ENABLED: False
[05/17 12:49:51 fastreid]: Full config saved to E:\Python\ML\AI_CUP\AICUP_Baseline_BoT-SORT\logs\AICUP_115\bagtricks_R50-ibn\config.yaml
C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torchvision\transforms\transforms.py:330: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
Traceback (most recent call last):
  File "fast_reid/tools/train_net.py", line 60, in <module>
    args=(args,),
  File ".\fast_reid\fastreid\engine\launch.py", line 71, in launch
    main_func(*args)
  File "fast_reid/tools/train_net.py", line 43, in main
    trainer = DefaultTrainer(cfg)
  File ".\fast_reid\fastreid\engine\defaults.py", line 203, in __init__
    data_loader = self.build_train_loader(cfg)
  File ".\fast_reid\fastreid\engine\defaults.py", line 402, in build_train_loader
    return build_reid_train_loader(cfg, combineall=cfg.DATASETS.COMBINEALL)
  File ".\fast_reid\fastreid\config\config.py", line 265, in wrapped
    return orig_func(**explicit_args)
  File ".\fast_reid\fastreid\data\build.py", line 98, in build_reid_train_loader
    pin_memory=True,
  File ".\fast_reid\fastreid\data\data_utils.py", line 152, in __init__
    local_rank
  File "C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torch\cuda\streams.py", line 36, in __new__
    with torch.cuda.device(device):
  File "C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torch\cuda\__init__.py", line 287, in __enter__
    self.prev_idx = torch.cuda.current_device()
  File "C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torch\cuda\__init__.py", line 552, in current_device
    _lazy_init()
  File "C:\Users\OWNER\anaconda3\envs\botsort\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ricky-696** [comment]
1. 你電腦的環境變數就是設定成Python，所以以後直接打Python就好不用加後面的3
2. 你Torch裝成只有CPU的版本了，你Torch也要安裝對應的CUDA版本才行，我自己是用[torch1.13.1+cu117](https://pytorch.org/get-started/previous-versions/)
