### ISSUE TITLE
執行requirements.txt一直出現numpy 沒有安裝的狀態！但已經安裝過，

### ISSUE THREAD

**Issue by 410510009** [ricky-696/AICUP_Baseline_BoT-SORT#8]
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: opencv-python in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 2)) (4.9.0.80)
Collecting loguru (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 3))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting scikit-image (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 4))
  Using cached scikit_image-0.23.2-cp310-cp310-macosx_10_9_x86_64.whl.metadata (14 kB)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 6)) (4.66.2)
Requirement already satisfied: torchvision>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 7)) (0.17.2)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 8)) (9.3.0)
Requirement already satisfied: thop in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 9)) (0.1.1.post2209072238)
Collecting ninja (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 10))
  Using cached ninja-1.11.1.1-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl.metadata (5.3 kB)
Collecting tabulate (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 11))
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting tensorboard (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 12))
  Using cached tensorboard-2.16.2-py3-none-any.whl.metadata (1.6 kB)
Collecting lap (from -r /Users/changshieping/Desktop/Python/AI_Cup/AICUP_Baseline_BoT-SORT-main/requirements.txt (line 13))
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 127, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/qv/bljp3kwx3011zzn6m1011qv40000gn/T/pip-build-env-qu9yobqc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/qv/bljp3kwx3011zzn6m1011qv40000gn/T/pip-build-env-qu9yobqc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/qv/bljp3kwx3011zzn6m1011qv40000gn/T/pip-build-env-qu9yobqc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 236, in <module>
        File "<string>", line 220, in setup_package
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by ricky-696** [comment]
哈囉~
你的狀況是`lap`這個套件找不到`numpy`這個套件，你先用輸入`pip list` 確認numpy是有正確安裝的，
![image](https://github.com/ricky-696/AICUP_Baseline_BoT-SORT/assets/62836757/dde1a055-7184-4d90-89e7-155d190f1687)

我的環境是安裝`lap==0.4.0`，你試著直接去Terminal下以下指令:

- `pip install lap==0.4.0`

看看能不能解決你的問題。
